version: '3.3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn vio.wsgi:application --bind 0.0.0.0:8000 --workers 3 --log-level debug
    volumes:
      - static_volume:/home/vio/web/staticfiles
      - media_volume:/home/vio/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - mysql

  mysql:
    restart: always
    image: mysql:latest
    container_name: dev_mysql
    volumes:
      - "./db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file:
      - .env.prod
    # environment:
    #   MYSQL_USER: user
    #   MYSQL_PASSWORD: user
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: default_schema

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/vio/web/staticfiles
      - media_volume:/home/vio/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
