# Generated by Django 3.2.10 on 2022-01-07 03:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vioapp', '0002_auto_20220106_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
